### ISSUE TITLE
Minecraft 1.18. Update

### ISSUE THREAD

**Issue by PetyXbron** [jacky8399/FakeSnow#2]
Will be this plugin updated to **Minecraft 1.18**? (Java 17)
It's Christmas time, so why not? 😄

**Comment by jacky8399** [comment]
1.18 changed the way biomes are sent to the client (again), so for now I've released a 1.17 version on spigot. 1.18 would take quite a while since I can't find a neat way to modify biome data in 1.18 using ProtocolLib.

**Comment by PetyXbron** [comment]
Doesn't ProtocolLib support 1.18.1 in stable verison already? Look at ProtocolLib commit [74833f8](https://github.com/dmulloy2/ProtocolLib/commit/74833f86806de435284a3fc22acb63c6d086d26d) by [derklaro](https://github.com/derklaro).

**Comment by jacky8399** [comment]
But the biome data is stored in a new paletted container which is basically impossible to intercept with ProtocolLib. The problem isn't that ProtocolLib doesn't support 1.18, it's that ProtocolLib doesn't provide the wrappers for dealing with the new packet format. (See dmulloy2/ProtocolLib#1469 for a similar issue)

**Comment by jacky8399** [comment]
The plugin has been updated to 1.19
