### ISSUE TITLE
Update to 1.20.x

### ISSUE THREAD

**Issue by Fantomrat** [jacky8399/FakeSnow#5]

**Comment by jacky8399** [comment]
1.20 support has been added in [1.3.2](https://github.com/jacky8399/FakeSnow/releases/tag/1.3.2).

**Comment by PetyXbron** [comment]
Hi @jacky8399. It is not currently working for me while using the 1.20.2 version. It might connect with Protocollib or ViaVersion.
Here's the error log: [pastebin.com/zTYpNtm3](https://pastebin.com/zTYpNtm3).
I just set the flag with
```
/rg flag -w "spawn" -h 7 __global__ custom-weather-type snow
```
After `/fakesnow refreshregions` it didn't show, so I tried to relog but got the error. All players that visited that world got a black screen.

**Comment by jacky8399** [comment]
I can't seem to replicate the issue with a 1.20.2 Paper server running ViaVersion and ViaBackwards 4.8.1, but I have identified a potential fix. Can you try this jar?
[FakeSnow-1.3.2-1.20.2fix.jar.zip](https://github.com/jacky8399/FakeSnow/files/13536860/FakeSnow-1.3.2-1.20.2fix.jar.zip)

**Comment by PetyXbron** [comment]
Yeah, this seems to work! Without any errors / kicks / black screens. Thank you! 

But I just realised that I had weather turned off by MultiVerse world management. But it should not be the issue. And then I used `/weather storm` by Essentials to set rainy weather and after that I finally saw the snow. Btw, will that weather stay on forever? I hope so.

**Comment by jacky8399** [comment]
You can make a region rain with `/region flag <id> weather-lock rain`
