### ISSUE TITLE
Does not work after moving between worlds

### ISSUE THREAD

**Issue by Vyacheslav73195** [jacky8399/FakeSnow#6]
After teleporting between worlds, the Snow_taiga biome remains, but the snow is not displayed. If you re-upload to the server, then everything works as expected. (Before the new movement between worlds)
WorldGuard - true (And configured correctly)
Multiverse Core is used
Server version - Paper 1.20.1

**Comment by Vyacheslav73195** [comment]
(There are no errors in the console)

**Comment by jacky8399** [comment]
The world needs to be raining for you to see the snow. If the biome is snowy_taiga, the plugin is working as intended. Try locking the weather with `/region flag <id> weather-lock rain`.

**Comment by Vyacheslav73195** [comment]
I've already done it all. The weather is blocked, snowmen are dying from the rain. The problem is observed only if the player moves between worlds. Up to the point that two players standing next to each other, one has snow, and the other does not.

**Comment by jacky8399** [comment]
This seems to be an issue with how WorldGuard handles `weather-lock`. Entering a region via portals doesn't seem to update the weather for the player, leading to buggy weather. You can see that the snow works if you leave and reenter the region. Unfortunately this is not something I can fix on my end, and you should create an issue on WorldGuard's issue tracker.
